fix %pretrans on first install; rel 3
if /etc/ssl/certs does not exist yet stat() returns nil:

error: lua script failed: [string "%pretrans(ca-certificates-20211016-2.noarch)"]:2: attempt to index a nil value (local 'mode')